# Generated by Django 4.2.10 on 2025-03-12 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='заголовок')),
                ('description', models.TextField(verbose_name='описание')),
                ('duration_minutes', models.IntegerField(default=15, verbose_name='продолжительность (минуты)')),
                ('category', models.CharField(choices=[('rest', 'Отдых'), ('sleep', 'Сон'), ('exercise', 'Физическая активность'), ('mindfulness', 'Осознанность'), ('social', 'Социальная активность'), ('work_balance', 'Баланс работы')], default='rest', max_length=50, verbose_name='категория')),
                ('is_quick', models.BooleanField(default=False, help_text='Может быть выполнена быстро, например, в перерыве между работой', verbose_name='быстрая рекомендация')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'рекомендация',
                'verbose_name_plural': 'рекомендации',
            },
        ),
        migrations.CreateModel(
            name='RecommendationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('description', models.TextField(verbose_name='описание')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='иконка')),
            ],
            options={
                'verbose_name': 'тип рекомендации',
                'verbose_name_plural': 'типы рекомендаций',
            },
        ),
        migrations.CreateModel(
            name='UserRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'В ожидании'), ('accepted', 'Принята'), ('completed', 'Выполнена'), ('rejected', 'Отклонена')], default='pending', max_length=20, verbose_name='статус')),
                ('reason', models.TextField(blank=True, verbose_name='причина')),
                ('user_feedback', models.TextField(blank=True, verbose_name='отзыв пользователя')),
                ('user_rating', models.IntegerField(blank=True, help_text='Оценка от 1 до 5', null=True, verbose_name='оценка пользователя')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='дата выполнения')),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendations.recommendation', verbose_name='рекомендация')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'рекомендация пользователя',
                'verbose_name_plural': 'рекомендации пользователей',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='recommendation',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='recommendations.recommendationtype', verbose_name='тип'),
        ),
    ]
