# Generated by Django 4.2.10 on 2025-02-28 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='дата')),
                ('duration_hours', models.FloatField(verbose_name='продолжительность (часов)')),
                ('breaks_count', models.IntegerField(default=0, verbose_name='количество перерывов')),
                ('breaks_total_minutes', models.IntegerField(default=0, verbose_name='общая продолжительность перерывов (минуты)')),
                ('productivity', models.IntegerField(blank=True, help_text='Оценка продуктивности от 1 до 10', null=True, verbose_name='продуктивность')),
                ('notes', models.TextField(blank=True, verbose_name='заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_activities', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'рабочая активность',
                'verbose_name_plural': 'рабочие активности',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='StressLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(help_text='Уровень стресса от 0 до 100', verbose_name='уровень стресса')),
                ('notes', models.TextField(blank=True, verbose_name='заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stress_level_records', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'уровень стресса',
                'verbose_name_plural': 'уровни стресса',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SleepRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='дата')),
                ('duration_hours', models.FloatField(verbose_name='продолжительность (часов)')),
                ('quality', models.IntegerField(blank=True, help_text='Оценка качества сна от 1 до 10', null=True, verbose_name='качество сна')),
                ('notes', models.TextField(blank=True, verbose_name='заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sleep_records', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'запись о сне',
                'verbose_name_plural': 'записи о сне',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='BurnoutRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='дата')),
                ('risk_level', models.IntegerField(help_text='Уровень риска выгорания от 0 до 100', verbose_name='уровень риска')),
                ('work_hours_factor', models.FloatField(default=0.0, verbose_name='фактор рабочих часов')),
                ('sleep_factor', models.FloatField(default=0.0, verbose_name='фактор сна')),
                ('stress_factor', models.FloatField(default=0.0, verbose_name='фактор стресса')),
                ('breaks_factor', models.FloatField(default=0.0, verbose_name='фактор перерывов')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='burnout_risks', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'риск выгорания',
                'verbose_name_plural': 'риски выгорания',
                'ordering': ['-date'],
            },
        ),
    ]
