# Generated by Django 4.2.10 on 2025-03-12 08:27

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='burnoutrisk',
            options={},
        ),
        migrations.RemoveField(
            model_name='burnoutrisk',
            name='breaks_factor',
        ),
        migrations.RemoveField(
            model_name='burnoutrisk',
            name='sleep_factor',
        ),
        migrations.RemoveField(
            model_name='burnoutrisk',
            name='stress_factor',
        ),
        migrations.RemoveField(
            model_name='burnoutrisk',
            name='work_hours_factor',
        ),
        migrations.AlterField(
            model_name='burnoutrisk',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='burnoutrisk',
            name='risk_level',
            field=models.IntegerField(help_text='Уровень риска выгорания (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='burnoutrisk',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='burnout_risks', to=settings.AUTH_USER_MODEL),
        ),
    ]
