# Generated by Django 4.2.10 on 2025-03-14 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_alter_burnoutrisk_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='burnoutrisk',
            name='factors',
            field=models.JSONField(blank=True, default=dict, help_text='Факторы риска выгорания и их значения', null=True),
        ),
        migrations.AddField(
            model_name='burnoutrisk',
            name='recommendations',
            field=models.JSONField(blank=True, default=list, help_text='Рекомендации по предотвращению выгорания', null=True),
        ),
    ]
